name: Font_Install_Demo
configs:
  Debug: debug
  Release: release
options:
  deploymentTarget:
    iOS: "13.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_NAME: "$(TARGET_NAME)"
    CURRENT_PROJECT_VERSION: 1
    IPHONEOS_DEPLOYMENT_TARGET: 13.1
schemes:
  Debug:
    build:
      targets:
        Font_Install_Demo: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
  Release:
    build:
      targets:
        Font_Install_Demo: all
    run:
      config: Release
    test:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
targets:
  Font_Install_Demo:
    type: application
    platform: iOS
    sources:
      - path: Font_Install_Demo
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
        CODE_SIGN_ENTITLEMENTS: Font_Install_Demo/Font_Install_Demo.entitlements
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: Font_Install_Demo/Info.plist
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          PRODUCT_NAME: "$TARGET_NAME-debug"
          PRODUCT_BUNDLE_IDENTIFIER: "h.t.Font-Install-Demo.debug"
          DEVELOPMENT_TEAM: R82WJ5W3TV
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
          PRODUCT_NAME: $TARGET_NAME
          PRODUCT_BUNDLE_IDENTIFIER: "h.t.Font-Install-Demo"
          DEVELOPMENT_TEAM: R82WJ5W3TV
    scheme:
      testTargets:
        - Font_Install_DemoTests
        - Font_Install_DemoUITests
  Font_Install_DemoTests:
    type: bundle.unit-test
    platform: iOS
    sources: Font_Install_DemoTests
    dependencies:
      - target: Font_Install_Demo
  Font_Install_DemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: Font_Install_DemoUITests
    dependencies:
      - target: Font_Install_DemoUITests
